app/Http/routes.php
<?php

// Application routes
Route::group(['namespace' => 'Application', 'middleware' => 'app'], function()
{
    Route::get('/', ['as' => 'root', 'uses' => 'HomeController@index']);
    Route::get('article/{article}',  ['as' => 'article', 'uses' => 'ArticleController@index']);
    Route::get('page/{page}',  ['as' => 'page', 'uses' => 'PageController@index']);
    Route::get('category/{category}',  ['as' => 'category', 'uses' => 'CategoryController@index']);
    Route::post('language/change', ['as' => 'app.language.change' , 'uses' => 'LanguageController@postChange']);
});

// Auth routes
Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function()
{
    Route::get('/', ['as' => 'auth.root', 'uses' => 'AuthController@getLogin']);
    Route::get('login',  ['as' => 'auth.login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth.login', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'auth.logout', 'uses' => 'AuthController@getLogout']);
});

// Password routes
Route::group(['prefix' => 'password', 'namespace' => 'Auth'], function()
{
    Route::get('email',  ['as' => 'password.email', 'uses' => 'PasswordController@getEmail']);
    Route::post('email', ['as' => 'password.email', 'uses' => 'PasswordController@postEmail']);
    Route::get('reset/{token}',  ['as' => 'password.reset', 'uses' => 'PasswordController@getReset']);
    Route::post('reset', ['as' => 'password.reset', 'uses' => 'PasswordController@postEmail']);
});

// Admin routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function()
{
    Route::get('user/table', ['as'=>'admin.user.table', 'uses'=>'UserController@getDatatable']);
    Route::get('article/table', ['as'=>'admin.article.table', 'uses'=>'ArticleController@getDatatable']);
    Route::get('category/table', ['as'=>'admin.category.table', 'uses'=>'CategoryController@getDatatable']);
    Route::get('language/table', ['as'=>'admin.language.table', 'uses'=>'LanguageController@getDatatable']);
    Route::group(['middleware' => 'auth'], function(){
        Route::get('/', ['as' => 'admin.root', 'uses' => 'DashboardController@index']);
        Route::resource('language', 'LanguageController');
        Route::post('language/change', ['as' => 'admin.language.change' , 'uses' => 'LanguageController@postChange']);
        Route::resource('user', 'UserController');
        Route::resource('article', 'ArticleController');
        Route::resource('category', 'CategoryController');
        Route::resource('page', 'PageController');
        Route::post('page/order', ['as' => 'admin.page.order' , 'uses' => 'PageController@postOrder']);
        Route::get('setting', ['as' => 'admin.setting.index', 'uses' => 'SettingController@getSettings']);
        Route::patch('setting/{setting}', ['as' => 'admin.setting.update', 'uses' => 'SettingController@patchSettings']);
    });
});

resources/views/partials/admin/header.blade.php
<section class="content-header">
    {!! header_title() !!}
    {!! breadcrumbs() !!}
</section>

resources/views/partials/admin/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        @include('partials.menu.admin', ['items'=> $menu_admin->roots()])
    </section>
</aside>

resources/views/partials/admin/tinymce.blade.php
<script src="{{ url( 'packages/tinymce/tinymce.min.js' ) }}" type="text/javascript"></script>
<script>
    tinymce.init({
        selector: "textarea",
        theme: "modern",
        menubar : false,
        relative_urls: false,
        forced_root_block: false, // Start tinyMCE without any paragraph tag
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars media nonbreaking",
            "table contextmenu directionality paste textcolor"
        ],
        toolbar1: "bold italic underline hr | link unlink |  image media | forecolor backcolor  | bullist numlist outdent indent | code | preview | styleselect",
        entity_encoding: "raw",
        file_picker_callback : elFinderBrowser
    });

    function elFinderBrowser(callback, value, meta) {
        var request = "{{ route('elfinder.tinymce4') }}";
        tinymce.activeEditor.windowManager.open({
            title: '{{  trans('admin.elfinder') }}',
            url: request,
            width: 900,
            height: 450,
            resizable: 'yes'
        }, {
            oninsert: function (url) {
                callback(url);
            }
        });
        return false;
    }
</script>

resources/views/partials/admin/top.blade.php
<header class="main-header">
    <a href="{{ route('admin.root') }}" class="logo"> {{ trans('admin.title')  }}</a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img class="user-image img-circle" src="{{ !empty($user->picture) ? $user->picture : 'https://ssl.gstatic.com/accounts/ui/avatar_2x.png' }}" alt="{{ Auth::user()->name  }}" />
                        <span class="hidden-xs">{{ Auth::user()->name  }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img class="img-circle" src="{{ !empty($user->picture) ? $user->picture : 'https://ssl.gstatic.com/accounts/ui/avatar_2x.png' }}" alt="{{ Auth::user()->name  }}" />
                            <p>{{ Auth::user()->name  }}</p>
                            @include('partials.common.languages', ['languages' => Config::get('languages'), 'route' => 'admin.language.change' ])
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.user.edit', ['id' => Auth::user()->id])  }}" class="btn btn-default btn-flat">{{ trans('admin.profile') }}</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('auth.logout') }}" class="btn btn-default btn-flat">{{ trans('auth.logout') }}</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>